services:
  backend:
    container_name: flickzy-api-dev
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    image: flickzy-dev
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - ./backend/.env
    networks:
      - go-flickzy
    # dns:
    #   - 8.8.8.8
    #   - 1.1.1.1

  db:
    image: postgres:17.5-alpine3.22
    container_name: flickzy-db
    ports:
      - "5431:5432"
    env_file:
      - ./backend/.env
    volumes:
      - flickzy-db-data:/var/lib/postgresql/data
    networks:
      - go-flickzy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d flickzy"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  redis:
    image: redis:8.0.2-alpine
    container_name: flickzy-redis
    ports:
      - "6378:6379"
    networks:
      - go-flickzy
    env_file:
      - ./backend/.env

networks:
  go-flickzy:
    driver: bridge

volumes:
  flickzy-db-data:
