FROM golang:1.24-alpine3.22

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN apk add curl bash git \
 && export GOBIN=/usr/local/bin \
 && go install github.com/pressly/goose/v3/cmd/goose@latest \
 && go install github.com/air-verse/air@latest \
 && go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest

EXPOSE 8080

CMD [ "air" ]