// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID        pgtype.UUID
	Email     string
	Username  string
	ApiToken  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Userotp struct {
	ID        pgtype.UUID
	Email     string
	Otp       int32
	ExpiresAt pgtype.Timestamptz
}
