// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Comment struct {
	ID          pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	PublishedAt pgtype.Timestamptz
	Description pgtype.Text
	Blob        pgtype.Text
	Likes       pgtype.Int4
	PostID      pgtype.UUID
	UserID      pgtype.UUID
}

type Post struct {
	ID          pgtype.UUID
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	Likes       pgtype.Int4
	Sharecount  pgtype.Int4
	Repost      pgtype.Int4
	Blob        pgtype.Text
	UserID      pgtype.UUID
	PublishedAt pgtype.Timestamptz
}

type User struct {
	ID        pgtype.UUID
	Email     string
	Username  string
	ApiToken  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Userotp struct {
	Email     string
	Otp       int32
	ExpiresAt pgtype.Timestamptz
}
